users = User.create([
  { username: "pikachu", email: "pik@chu.com", password: "whatever" },
  { username: "charmander", email: "char@mander.com", password: "whatever" },
  { username: "porygon", email: "pory@gon.com", password: "whatever" },
  { username: "abra", email: "ab@ra.com", password: "whatever" },
  { username: "magikarp", email: "magi@karp.com", password: "whatever" },
  { username: "mrmime", email: "mr@mime.com", password: "whatever" },
  { username: "ditto", email: "di@tto.com", password: "whatever"}
])
avatars = ["pika.png", "charmander.png", "porygon.png", "abra.png", "magikarp.png", "mime.png", "ditto.png"]
User.all.each_with_index do |user, idx|
  user.image = File.new(File.join(Rails.root, 'app', 'assets', 'images', avatars[idx]))
  user.save!
end
description = "Lorem ipsum dolor sit amet, erat autem noster ea duo. Vide quidam ea nec. Ei quo mentitum convenire consetetur, cu eam lorem laoreet persecuti. Elit assum petentium in has, corpora suavitate tincidunt eu cum. Cu eum cetero persecuti, vix regione aliquam sententiae in, odio graecis singulis ne qui. Sit assum ludus voluptaria ei, sonet antiopam in has. Nam aliquid menandri et. Debet atomorum eu quo, et nec nostro scaevola probatus. Vide elit discere ei est. Dictas ancillae id per, ius probo reprimique id, te mundi interpretaris sit. Illud consul ridens eu has, ex aperiam deseruisse duo. Ei nec denique conclusionemque. Vel id lorem maiestatis, pro cu veniam singulis. Veniam ocurreret cu sea. Per id enim dicunt fuisset, eu usu habeo malis imperdiet. Has tamquam alterum laoreet no. Ne libris vivendum neglegentur per, ne est choro maiorum. Eos ad conceptam deseruisse, meliore electram gloriatur at vis, eam reque debitis volumus ut. Eum eu posse volutpat hendrerit, et ceteros sententiae eos, no vidisse torquatos pro. No alterum voluptaria cum, quo nisl audiam id. An novum inermis dolores usu. Vix ea hinc doctus quaestio. Eum id magna perfecto recteque, porro minim voluptaria vix te, mea sonet exerci vidisse ei. Dicat liberavisse accommodare cum cu. Libris suscipit adversarium in vis, an enim commodo scriptorem his. Usu ut nisl ignota, vim vide altera concludaturque ea"

groups = Group.create([
  { title: "Digimon Fan Club", moderator_id: 1, description: description, city: "Jersey City", state: "NJ", lat: 40.72815759999999, lng: -74.0776417 },
  { title: "ESP Enthusiasts", moderator_id: 4, description: description, city: "Philadelphia", state: "PA", lat: 39.9525839, lng: -75.1652215 },
  { title: "Splash", moderator_id: 5, description: description, city: "New York", state: "NY", lat: 40.7127837, lng: -74.0059413 },
  { title: "Mimes of Hoboken", moderator_id: 6, description: description, city: "Hoboken", state: "NJ", lat: 40.7439905, lng: -74.0323626 },
  { title: "Fennel Fox Fans", moderator_id: 2, description: description, city: "Newark", state: "NJ", lat: 40.735657, lng: -74.1723667 },
  { title: "Citizens Against Breakfast", moderator_id: 7, description: description, city: "Newport", state: "NJ", lat: 39.2968298, lng: -75.1769161},
  { title: "Amateur Curlers", moderator_id: 4, description: description, city: "Greenville", state: "NJ", lat: 40.6987935, lng: -74.0916944 },
  { title: "Lemur Lovers", moderator_id: 1, description: description, city: "Farmingdale", state: "NY", lat: 40.7325997, lng: -73.4454009 },
  { title: "Stamp Collectors", moderator_id: 6, description: description, city: "Amityville", state: "NY", lat: 40.6789893, lng: -73.4170673 }
])

memberships = Membership.create([
  { group_id: 1, member_id: 1 },
  { group_id: 1, member_id: 2 },
  { group_id: 1, member_id: 3 },
  { group_id: 1, member_id: 4 },
  { group_id: 1, member_id: 5 },
  { group_id: 2, member_id: 3 },
  { group_id: 2, member_id: 4 },
  { group_id: 2, member_id: 1 },
  { group_id: 3, member_id: 5 },
  { group_id: 3, member_id: 2 },
  { group_id: 3, member_id: 1 },
  { group_id: 4, member_id: 3 },
  { group_id: 4, member_id: 4 },
  { group_id: 4, member_id: 5 },
  { group_id: 4, member_id: 6 },
  { group_id: 4, member_id: 2 },
  { group_id: 5, member_id: 7 },
  { group_id: 5, member_id: 2 },
  { group_id: 5, member_id: 6 },
  { group_id: 5, member_id: 3 },
  { group_id: 5, member_id: 5 },
  { group_id: 5, member_id: 1 },
  { group_id: 6, member_id: 7 },
  { group_id: 6, member_id: 3 },
  { group_id: 6, member_id: 2 },
  { group_id: 7, member_id: 4 },
  { group_id: 7, member_id: 1 },
  { group_id: 7, member_id: 2 },
  { group_id: 7, member_id: 3 },
  { group_id: 7, member_id: 5 },
  { group_id: 7, member_id: 6 },
  { group_id: 7, member_id: 7 },
  { group_id: 8, member_id: 1 },
  { group_id: 8, member_id: 7 },
  { group_id: 8, member_id: 4 },
  { group_id: 8, member_id: 2 },
  { group_id: 8, member_id: 5 },
  { group_id: 9, member_id: 6 },
  { group_id: 9, member_id: 5 },
  { group_id: 9, member_id: 3 },
])

event_description = "Bacon ipsum dolor amet drumstick biltong tri-tip shoulder doner venison shank beef leberkas sausage. Tenderloin venison shankle prosciutto sausage spare ribs hamburger alcatra tongue. Flank ham short ribs, hamburger filet mignon t-bone biltong frankfurter. Doner venison drumstick salami ribeye strip steak fatback frankfurter. Shoulder prosciutto swine ground round ham hock turkey, tenderloin drumstick andouille kevin. Chuck meatloaf kielbasa cupim sirloin boudin pastrami turkey beef ribs sausage venison swine. Picanha jerky corned beef swine, meatball brisket capicola jowl. Pork bresaola meatloaf shank turducken cow. Chicken beef ribs doner, porchetta ribeye ham picanha. Corned beef pig venison, hamburger rump fatback pancetta swine prosciutto short ribs capicola ham hock. Short ribs bresaola picanha cow, porchetta shankle chuck corned beef tri-tip spare ribs fatback pork chop landjaeger. Biltong ground round pork belly, turducken leberkas picanha t-bone bacon hamburger ribeye. Short loin boudin alcatra, spare ribs hamburger strip steak andouille doner pork belly pancetta corned beef jerky."

events = Event.create([
  { group_id: 1, title: "First Meetup", description: event_description, start_time: "2016-08-26 01:00", end_time: "2016-08-26 14:00" },
  { group_id: 1, title: "Last Meetup", description: event_description, start_time: "2016-08-27 01:00", end_time: "2016-08-27 14:00" },
  { group_id: 1, title: "Meetup Reunion", description: event_description, start_time: "2016-08-15 02:00", end_time: "2016-08-15 14:30" },
  { group_id: 1, title: "Second Reunion", description: event_description, start_time: "2016-09-01 03:00", end_time: "2016-09-01 15:00" },
  { group_id: 1, title: "Farewell Meetup", description: event_description, start_time: "2016-09-20 04:00", end_time: "2016-09-20 15:30" },
  { group_id: 1, title: "Follow up Meetup", description: event_description, start_time: "2016-09-26 05:00", end_time: "2016-09-26 16:00" },
  { group_id: 2, title: "Ice Cream Social", description: event_description, start_time: "2016-08-25 11:00", end_time: "2016-08-25 12:00" },
  { group_id: 2, title: "Orientation", description: event_description, start_time: "2016-08-26 01:00", end_time: "2016-09-26 14:00" },
  { group_id: 2, title: "Field Day", description: event_description, start_time: "2016-09-06 02:00", end_time: "2016-09-06 14:30" },
  { group_id: 2, title: "Public Outreach", description: event_description, start_time: "2016-09-16 03:00", end_time: "2016-09-16 15:00" },
  { group_id: 2, title: "Picnic", description: event_description, start_time: "2016-09-26 04:00", end_time: "2016-09-26 15:30" },
  { group_id: 2, title: "Flag Football", description: event_description, start_time: "2016-10-11 05:00", end_time: "2016-10-11 16:00" },
  { group_id: 3, title: "Movie Night on the Lawn", description: event_description, start_time: "2016-08-23 01:00", end_time: "2016-08-23 14:00" },
  { group_id: 3, title: "LAN Party", description: event_description, start_time: "2016-08-24 02:00", end_time: "2016-08-24 14:30" },
  { group_id: 3, title: "Drum Cirle", description: event_description, start_time: "2016-09-07 03:00", end_time: "2016-09-07 15:00" },
  { group_id: 3, title: "Fitness Day", description: event_description, start_time: "2016-09-19 04:00", end_time: "2016-09-19 15:30" },
  { group_id: 3, title: "Pizza Party", description: event_description, start_time: "2016-09-26 05:00", end_time: "2016-09-26 16:00" },
  { group_id: 3, title: "BBQ", description: event_description, start_time: "2016-09-25 10:00", end_time: "2016-09-25 11:00" },
  { group_id: 4, title: "Annual Award Ceremony", description: event_description, start_time: "2016-08-14 01:00", end_time: "2016-08-14 14:00" },
  { group_id: 4, title: "Street Campaign", description: event_description, start_time: "2016-08-18 02:00", end_time: "2016-08-18 14:30" },
  { group_id: 4, title: "Pet Swap", description: event_description, start_time: "2016-08-26 03:00", end_time: "2016-08-26 15:00" },
  { group_id: 4, title: "Bingo Night", description: event_description, start_time: "2016-09-07 04:00", end_time: "2016-09-07 15:30" },
  { group_id: 4, title: "Sponsor Dinner", description: event_description, start_time: "2016-09-29 05:00", end_time: "2016-09-29 16:00" },
  { group_id: 4, title: "Street Race", description: event_description, start_time: "2016-09-30 07:00", end_time: "2016-09-30 09:00" },
  { group_id: 5, title: "Jump Rope for Heart", description: event_description, start_time: "2016-08-21 01:00", end_time: "2016-08-21 14:00" },
  { group_id: 5, title: "Breakfast for Dinner", description: event_description, start_time: "2016-08-26 02:00", end_time: "2016-08-26 14:30" },
  { group_id: 5, title: "Pumpkin Tossing Contest", description: event_description, start_time: "2016-09-01 03:00", end_time: "2016-09-01 15:00" },
  { group_id: 5, title: "Bake Sale", description: event_description, start_time: "2016-09-02 04:00", end_time: "2016-09-02 15:30" },
  { group_id: 5, title: "Pot Luck", description: event_description, start_time: "2016-09-03 05:00", end_time: "2016-09-03 16:00" },
  { group_id: 5, title: "Beach Day", description: event_description, start_time: "2016-09-04 06:00", end_time: "2016-09-04 16:30" },
  { group_id: 5, title: "Habitat For Humanity Day 1", description: event_description, start_time: "2016-09-05 07:00", end_time: "2016-09-05 17:00" },
  { group_id: 5, title: "Habitat For Humanity Day 2", description: event_description, start_time: "2016-09-06 08:00", end_time: "2016-09-06 17:30" },
  { group_id: 6, title: "Open Bar", description: event_description, start_time: "2016-08-23 01:00", end_time: "2016-08-23 14:00" },
  { group_id: 6, title: "Networking With the Stars", description: event_description, start_time: "2016-08-25 02:00", end_time: "2016-08-25 14:30" },
  { group_id: 6, title: "Karaoke Night", description: event_description, start_time: "2016-08-26 03:00", end_time: "2016-08-26 15:00" },
  { group_id: 6, title: "Dinner For Breakfast", description: event_description, start_time: "2016-09-15 04:00", end_time: "2016-09-15 15:30" },
  { group_id: 6, title: "Hudson River Cleanup", description: event_description, start_time: "2016-09-21 01:00", end_time: "2016-09-21 16:00" },
  { group_id: 7, title: "Yankees Game", description: event_description, start_time: "2016-08-20 01:00", end_time: "2016-08-20 14:00" },
  { group_id: 7, title: "Soup Kitchen", description: event_description, start_time: "2016-08-27 02:00", end_time: "2016-08-27 14:30" },
  { group_id: 7, title: "Clothing Drive", description: event_description, start_time: "2016-09-03 03:00", end_time: "2016-09-10 15:00" },
  { group_id: 7, title: "New York State Curling Championship Day 1", description: event_description, start_time: "2016-09-10 04:00", end_time: "2016-09-10 15:30" },
  { group_id: 7, title: "New York State Curling Championship Day 2", description: event_description, start_time: "2016-09-17 05:00", end_time: "2016-09-17 16:00" },
  { group_id: 8, title: "National Lemur Day", description: event_description, start_time: "2016-08-02 01:00", end_time: "2016-08-02 14:00" },
  { group_id: 8, title: "Free All the Lemurs from the Zoo", description: event_description, start_time: "2016-08-09 02:00", end_time: "2016-08-09 14:30" },
  { group_id: 8, title: "Lobster Dinner", description: event_description, start_time: "2016-08-16 03:00", end_time: "2016-08-16 15:00" },
  { group_id: 8, title: "Annual PFL Invitational", description: event_description, start_time: "2016-08-23 04:00", end_time: "2016-08-23 15:30" },
  { group_id: 8, title: "National Congress", description: event_description, start_time: "2016-08-30 05:00", end_time: "2016-08-26 16:00" },
  { group_id: 9, title: "Stamp Act Celebration", description: event_description, start_time: "2016-08-17 01:00", end_time: "2016-08-17 14:00" },
  { group_id: 9, title: "Pony Express Jubilee", description: event_description, start_time: "2016-08-24 02:00", end_time: "2016-08-24 14:30" },
  { group_id: 9, title: "Rage Against Email", description: event_description, start_time: "2016-08-31 03:00", end_time: "2016-08-31 15:00" },
  { group_id: 9, title: "Collection Appraisal", description: event_description, start_time: "2016-09-07 04:00", end_time: "2016-09-07 15:30" },
  { group_id: 9, title: "Silent Auction", description: event_description, start_time: "2016-09-14 05:00", end_time: "2016-09-14 16:00" },
])

rsvps = Rsvp.create([
  { event_id: 1, user_id: 1, attending: true },
  { event_id: 1, user_id: 2, attending: true },
  { event_id: 1, user_id: 3, attending: true },
  { event_id: 1, user_id: 4, attending: true },
  { event_id: 1, user_id: 5, attending: true },
  { event_id: 2, user_id: 6, attending: true },
  { event_id: 2, user_id: 7, attending: true },
  { event_id: 2, user_id: 1, attending: true },
  { event_id: 2, user_id: 2, attending: true },
  { event_id: 2, user_id: 3, attending: true },
  { event_id: 2, user_id: 4, attending: true },
  { event_id: 2, user_id: 5, attending: true },
  { event_id: 3, user_id: 6, attending: true },
  { event_id: 3, user_id: 7, attending: true },
  { event_id: 4, user_id: 1, attending: true },
  { event_id: 4, user_id: 2, attending: true },
  { event_id: 4, user_id: 3, attending: true },
  { event_id: 5, user_id: 4, attending: true },
  { event_id: 5, user_id: 5, attending: true },
  { event_id: 5, user_id: 6, attending: true },
  { event_id: 5, user_id: 7, attending: true },
  { event_id: 6, user_id: 1, attending: true },
  { event_id: 7, user_id: 2, attending: true },
  { event_id: 7, user_id: 3, attending: true },
  { event_id: 8, user_id: 4, attending: true },
  { event_id: 8, user_id: 5, attending: true },
  { event_id: 8, user_id: 6, attending: true },
  { event_id: 8, user_id: 7, attending: true },
  { event_id: 8, user_id: 1, attending: true },
  { event_id: 9, user_id: 2, attending: true },
  { event_id: 9, user_id: 3, attending: true },
  { event_id: 9, user_id: 4, attending: true },
  { event_id: 9, user_id: 5, attending: true },
  { event_id: 9, user_id: 6, attending: true },
  { event_id: 9, user_id: 7, attending: true },
  { event_id: 10, user_id: 1, attending: true },
  { event_id: 12, user_id: 2, attending: true },
  { event_id: 12, user_id: 3, attending: true },
  { event_id: 12, user_id: 4, attending: true },
  { event_id: 12, user_id: 5, attending: true },
  { event_id: 13, user_id: 6, attending: true },
  { event_id: 13, user_id: 7, attending: true },
  { event_id: 13, user_id: 1, attending: true },
  { event_id: 13, user_id: 2, attending: true },
  { event_id: 13, user_id: 3, attending: true },
  { event_id: 14, user_id: 4, attending: true },
  { event_id: 15, user_id: 5, attending: true },
  { event_id: 15, user_id: 6, attending: true },
  { event_id: 15, user_id: 7, attending: true },
  { event_id: 16, user_id: 1, attending: true },
  { event_id: 16, user_id: 2, attending: true },
  { event_id: 17, user_id: 3, attending: true },
  { event_id: 17, user_id: 4, attending: true },
  { event_id: 17, user_id: 5, attending: true },
  { event_id: 17, user_id: 6, attending: true },
  { event_id: 18, user_id: 7, attending: true },
  { event_id: 18, user_id: 1, attending: true },
  { event_id: 18, user_id: 2, attending: true },
  { event_id: 19, user_id: 3, attending: true },
  { event_id: 19, user_id: 4, attending: true },
  { event_id: 19, user_id: 5, attending: true },
  { event_id: 19, user_id: 6, attending: true },
  { event_id: 19, user_id: 7, attending: true },
  { event_id: 19, user_id: 1, attending: true },
  { event_id: 19, user_id: 2, attending: true },
  { event_id: 20, user_id: 3, attending: true },
  { event_id: 20, user_id: 4, attending: true },
  { event_id: 21, user_id: 5, attending: true },
  { event_id: 21, user_id: 6, attending: true },
  { event_id: 21, user_id: 7, attending: true },
  { event_id: 21, user_id: 1, attending: true },
  { event_id: 22, user_id: 2, attending: true },
  { event_id: 22, user_id: 3, attending: true },
  { event_id: 23, user_id: 4, attending: true },
  { event_id: 24, user_id: 5, attending: true },
  { event_id: 24, user_id: 6, attending: true },
  { event_id: 24, user_id: 7, attending: true },
  { event_id: 24, user_id: 1, attending: true },
  { event_id: 24, user_id: 2, attending: true },
  { event_id: 25, user_id: 3, attending: true },
  { event_id: 25, user_id: 4, attending: true },
  { event_id: 25, user_id: 5, attending: true },
  { event_id: 30, user_id: 6, attending: true },
  { event_id: 30, user_id: 7, attending: true },
  { event_id: 31, user_id: 1, attending: true },
  { event_id: 31, user_id: 2, attending: true },
  { event_id: 31, user_id: 3, attending: true },
  { event_id: 31, user_id: 4, attending: true },
  { event_id: 31, user_id: 5, attending: true },
  { event_id: 31, user_id: 6, attending: true },
  { event_id: 32, user_id: 7, attending: true },
  { event_id: 32, user_id: 1, attending: true },
  { event_id: 32, user_id: 2, attending: true },
  { event_id: 32, user_id: 3, attending: true },
  { event_id: 32, user_id: 4, attending: true },
  { event_id: 32, user_id: 5, attending: true },
  { event_id: 32, user_id: 6, attending: true },
  { event_id: 33, user_id: 7, attending: true },
  { event_id: 33, user_id: 1, attending: true },
  { event_id: 34, user_id: 2, attending: true },
  { event_id: 35, user_id: 3, attending: true },
  { event_id: 35, user_id: 4, attending: true },
  { event_id: 36, user_id: 5, attending: true },
  { event_id: 36, user_id: 6, attending: true },
  { event_id: 36, user_id: 7, attending: true },
  { event_id: 36, user_id: 1, attending: true },
  { event_id: 37, user_id: 2, attending: true },
  { event_id: 37, user_id: 3, attending: true },
  { event_id: 37, user_id: 4, attending: true },
  { event_id: 38, user_id: 5, attending: true },
  { event_id: 38, user_id: 6, attending: true },
  { event_id: 38, user_id: 7, attending: true },
  { event_id: 38, user_id: 1, attending: true },
  { event_id: 39, user_id: 2, attending: true },
  { event_id: 39, user_id: 3, attending: true },
  { event_id: 39, user_id: 4, attending: true },
  { event_id: 40, user_id: 5, attending: true },
  { event_id: 40, user_id: 6, attending: true },
  { event_id: 41, user_id: 7, attending: true },
  { event_id: 41, user_id: 1, attending: true },
  { event_id: 42, user_id: 2, attending: true },
  { event_id: 43, user_id: 3, attending: true },
  { event_id: 43, user_id: 4, attending: true },
  { event_id: 43, user_id: 5, attending: true },
  { event_id: 44, user_id: 6, attending: true },
  { event_id: 44, user_id: 7, attending: true },
  { event_id: 44, user_id: 1, attending: true },
  { event_id: 45, user_id: 2, attending: true },
  { event_id: 45, user_id: 3, attending: true },
  { event_id: 45, user_id: 4, attending: true },
  { event_id: 45, user_id: 5, attending: true },
  { event_id: 45, user_id: 6, attending: true },
  { event_id: 46, user_id: 7, attending: true },
  { event_id: 46, user_id: 1, attending: true },
  { event_id: 47, user_id: 2, attending: true },
  { event_id: 47, user_id: 3, attending: true },
  { event_id: 47, user_id: 4, attending: true },
  { event_id: 47, user_id: 5, attending: true },
  { event_id: 47, user_id: 6, attending: true },
  { event_id: 48, user_id: 7, attending: true },
  { event_id: 48, user_id: 1, attending: true },
  { event_id: 48, user_id: 2, attending: true },
  { event_id: 48, user_id: 3, attending: true },
  { event_id: 48, user_id: 4, attending: true },
  { event_id: 48, user_id: 5, attending: true },
  { event_id: 48, user_id: 6, attending: true },
  { event_id: 49, user_id: 7, attending: true },
  { event_id: 49, user_id: 1, attending: true },
  { event_id: 49, user_id: 2, attending: true },
  { event_id: 49, user_id: 3, attending: true },
  { event_id: 49, user_id: 4, attending: true },
  { event_id: 49, user_id: 5, attending: true },
  { event_id: 50, user_id: 6, attending: true },
  { event_id: 50, user_id: 7, attending: true },
  { event_id: 50, user_id: 1, attending: true },
  { event_id: 50, user_id: 2, attending: true },
  { event_id: 50, user_id: 3, attending: true },
  { event_id: 50, user_id: 4, attending: true },
  { event_id: 50, user_id: 5, attending: true },
  { event_id: 51, user_id: 6, attending: true },
  { event_id: 51, user_id: 7, attending: true },
  { event_id: 51, user_id: 1, attending: true },
  { event_id: 51, user_id: 2, attending: true },
  { event_id: 51, user_id: 3, attending: true },
  { event_id: 52, user_id: 4, attending: true },
  { event_id: 52, user_id: 5, attending: true },
  { event_id: 52, user_id: 6, attending: true },
  { event_id: 52, user_id: 7, attending: true },
  { event_id: 52, user_id: 1, attending: true },
  { event_id: 52, user_id: 2, attending: true },
  { event_id: 52, user_id: 3, attending: true },
])
