users = User.create([
  { username: "pikachu", email: "pik@chu.com", password: "whatever" },
  { username: "charmander", email: "char@mander.com", password: "whatever" },
  { username: "porygon", email: "pory@gon.com", password: "whatever" },
  { username: "abra", email: "ab@ra.com", password: "whatever" },
  { username: "magikarp", email: "magi@karp.com", password: "whatever" },
  { username: "mrmime", email: "mr@mime.com", password: "whatever" },
  { username: "ditto", email: "di@tto.com", password: "whatever"}
])
avatars = ["pika.png", "charmander.png", "porygon.png", "abra.png", "magikarp.png", "mime.png", "ditto.png"]
User.all.each_with_index do |user, idx|
  user.image = File.new(File.join(Rails.root, 'app', 'assets', 'images', avatars[idx]))
  user.save!
end

group_pictures = ["exodia.jpg", "spoon.jpeg", "splash.jpg", "mime.jpg", "fox.jpeg", "breakfast.jpg", "curling.png", "lemur.jpeg", "stamp.jpg"]
groups = Group.create([
  { title: "Digimon Fan Club", moderator_id: 1, description: "We are a bunch of Digimon fans. The greatest fighting monster franchise to ever come from Japan! Hang out with us if you love Digimon. We are a relaxed and friendly group of people always looking for new friends. Even if you aren't the biggest fan, stop on by ", city: "Jersey City", state: "NJ", lat: 40.72815759999999, lng: -74.0776417 },
  { title: "ESP Enthusiasts", moderator_id: 4, description: "Practice your ESP with us.", city: "Philadelphia", state: "PA", lat: 39.9525839, lng: -75.1652215 },
  { title: "Splash", moderator_id: 5, description: "If you love splashing in the water then Splash is for you. We also like to make exciting things happen around our city. We are the hottest Meetup in town right now! Stay cool with Splash.", city: "New York", state: "NY", lat: 40.7127837, lng: -74.0059413 },
  { title: "Mimes of Hoboken", moderator_id: 6, description: "In recent years, mimes have become somewhat of a novelty. Merely a French quirk of a byegone era. However, us mimes are a proud bunch, we keep our mime tradition alive. If you are a mime or aspiring mime, come out and hang with us! We are usually in Hoboken, but sometimes take trips to Jersey City and Manhattan to meet with other groups of mimes in the area.", city: "Hoboken", state: "NJ", lat: 40.7439905, lng: -74.0323626 },
  { title: "Fennec Fox Fans", moderator_id: 2, description: "Fennec Foxes are the CUTEST!!! We love fennec foxes. Did you know a fennec fox can jump straight up as high as 61 centimeters, even though they are only 20 centimeters tall?! They can also jump distances of 120 centimeters. What cool animals.", city: "Newark", state: "NJ", lat: 40.735657, lng: -74.1723667 },
  { title: "Citizens Against Breakfast", moderator_id: 7, description: "We are a group of concerned citizens about the widespread practice of consuming breakfast. Often pitched as 'the most important meal of the day', breakfast foods consist of foods high in bad cholesterol and sugar. Pancakes? Merely vessels to consume butter and syrup. Eggs and Bacon? Eat only eggs and bacon for a year and see if you survive. Breakfast is bad.", city: "Newport", state: "NJ", lat: 39.2968298, lng: -75.1769161},
  { title: "Amateur Curlers", moderator_id: 4, description: "We are people that like to go curling! Unfortunately, curling's popularity has gone down in recent years and it can be hard to find friends who will consistently play. If you are a diehard curling fan this group is for you!", city: "Greenville", state: "NJ", lat: 40.6987935, lng: -74.0916944 },
  { title: "Lemur Lovers", moderator_id: 1, description: "Lemurs are great. They do some cool stuff. You should join this group. We meet often and are very passionate about these majestic creatures.", city: "Farmingdale", state: "NY", lat: 40.7325997, lng: -73.4454009 },
  { title: "Stamp Collectors", moderator_id: 6, description: "We are the largest network of stamp collectors in Amityville area. We get together to swamp stamps and show off our coolest ones. If you are new to stamp collecting, or looking to get back into your old hobby, then this group is for you!", city: "Amityville", state: "NY", lat: 40.6789893, lng: -73.4170673 }
])
Group.all.each_with_index do |group, idx|
  group.image = File.new(File.join(Rails.root, 'app', 'assets', 'images', group_pictures[idx]))
  group.save!
end
memberships = Membership.create([
  { group_id: 1, member_id: 1 },
  { group_id: 1, member_id: 2 },
  { group_id: 1, member_id: 3 },
  { group_id: 1, member_id: 4 },
  { group_id: 1, member_id: 5 },
  { group_id: 2, member_id: 3 },
  { group_id: 2, member_id: 4 },
  { group_id: 2, member_id: 1 },
  { group_id: 3, member_id: 5 },
  { group_id: 3, member_id: 2 },
  { group_id: 3, member_id: 1 },
  { group_id: 4, member_id: 3 },
  { group_id: 4, member_id: 4 },
  { group_id: 4, member_id: 5 },
  { group_id: 4, member_id: 6 },
  { group_id: 4, member_id: 2 },
  { group_id: 5, member_id: 7 },
  { group_id: 5, member_id: 2 },
  { group_id: 5, member_id: 6 },
  { group_id: 5, member_id: 3 },
  { group_id: 5, member_id: 5 },
  { group_id: 5, member_id: 1 },
  { group_id: 6, member_id: 7 },
  { group_id: 6, member_id: 3 },
  { group_id: 6, member_id: 2 },
  { group_id: 7, member_id: 4 },
  { group_id: 7, member_id: 1 },
  { group_id: 7, member_id: 2 },
  { group_id: 7, member_id: 3 },
  { group_id: 7, member_id: 5 },
  { group_id: 7, member_id: 6 },
  { group_id: 7, member_id: 7 },
  { group_id: 8, member_id: 1 },
  { group_id: 8, member_id: 7 },
  { group_id: 8, member_id: 4 },
  { group_id: 8, member_id: 2 },
  { group_id: 8, member_id: 5 },
  { group_id: 9, member_id: 6 },
  { group_id: 9, member_id: 5 },
  { group_id: 9, member_id: 3 },
])

events = Event.create([
  { group_id: 1, title: "First Meetup", description: "We are going to be meeting up for the first time today! Please RSVP so we can get a good idea of how many will be attending so we can order the appropriate amount of food. If you are bringing any plus ones, please just shoot me an email! We have a few things to discuss, such as plans for the future and how we can get sponsored." start_time: "2016-08-26 01:00", end_time: "2016-08-26 14:00" },
  { group_id: 1, title: "Last Meetup", description: "This will be the last meeting before the Meetup Reunion. NO PLUS ONES ALLOWED!!!!!! This is a members only event. We must plan for our reunion. We will kick off the Meetup with food catered by Chipotle, followed by some ice cream for dessert. Afterward we will read the mninutes from our last Meetup to give us an idea of what we need to do for our reunion. This meeting will be a bit more formal than the last. But that is because we have a lot of planning to do. I look forward to seeing you all for our last Meetup before the reunion.", start_time: "2016-08-27 01:00", end_time: "2016-08-27 14:00" },
  { group_id: 1, title: "Meetup Reunion", description: "The Meetup Reunion event will be our chance to get together and talk about all the great memories we have had as a group. NO PLUS ONES!!!! See where fellow members are and what they are doing. We will feature a Guitar Hero tournament for the competitive among us. The grand prize is bragging rights and a $10 gift certficate to the iTunes store. Soft beverages will be served, otherwise BYOB. We will be partying all night long! One of our members has agreed to DJ for the evening so get ready for some cool tunes! We have also hired a juggling clown. Its going to be fun!", start_time: "2016-08-15 02:00", end_time: "2016-08-15 14:30" },
  { group_id: 1, title: "Second Reunion", description: "Our second reunion will be a good time for all! We will be watching movies and eating pizza. Feel free to bring some plus ones. Don't even bother letting me know, all are welcome! It is going to be a time for members and friends. We will also be swapping life hacks. We will also be hosting a Risk tournament this time around. Get ready for fun that will never end! There will be casual Jenga games as well.", start_time: "2016-09-01 03:00", end_time: "2016-09-01 15:00" },
  { group_id: 1, title: "Farewell Meetup", description: "This is it, time to say our farewells. This will be a very serious time for all of us so please wear your Sunday's best. No food or beverages will be served.", start_time: "2016-09-20 04:00", end_time: "2016-09-20 15:30" },
  { group_id: 1, title: "Follow up Meetup", description: "This meeting will be a time for reflection and also discuss our thoughts and feelings on how our time together has been. After this I will be starting a new Meetup and deleting this one. So I will get a head count of how many people will be interested in the new group. Please bring all your friends and family so hopefully the next group can be even better (could you imagine?!) than this one. Also we will have a brief awards ceremony where I will give out some trophies and a nice parting gift. This meeting will be all about YOU! the wonderful members. :)", start_time: "2016-09-26 05:00", end_time: "2016-09-26 16:00" },
  { group_id: 2, title: "Ice Cream Social", description: "A nice little get to know each other Meetup for our new group! An ice cream sundae station will be set up where we can all build our own sundaes! Please let me know if anyone has any allergies or other dietary restrictions. Should be a fun meeting!", start_time: "2016-08-25 11:00", end_time: "2016-08-25 12:00" },
  { group_id: 2, title: "Orientation", description: "After having gotten to know each other, we will need to get down to business. Orientation will include materials all members must take home and study to learn more about the group. We have a lot of work to do, people! So get ready for this nifty group! It will be a rich and rewarding experience.", start_time: "2016-08-26 01:00", end_time: "2016-09-26 14:00" },
  { group_id: 2, title: "Field Day", description: "After all that hard studying it will be time to get some fresh air with a field day! We will have multiple events, including, tug-of-war, egg toss, the gauntlet, frisbee golf, and much more! Medals will be given out to first, second, and third place teams. We will have plenty of complimentary Gatorade. Get ready to compete!", start_time: "2016-09-06 02:00", end_time: "2016-09-06 14:30" },
  { group_id: 2, title: "Public Outreach", description: "Our Public Outreach event is going to be a hard day's work! We will be hitting the streets of NYC to get the word out about our amazing group. We will be going out in groups of two. We need volunteers to coordinate routes through the city. I hope everyone can participate in this exciting event. Afterward we will regroup and grab some burgers on 12th street and talk about our favorite parts of the day!", start_time: "2016-09-16 03:00", end_time: "2016-09-16 15:00" },
  { group_id: 2, title: "Picnic", description: "We will be having a picnic in Washington Square Park. Family and friends are more than welcome to join! Everyone should plan on bringing a side. It will be $5 per group of people. BYOB for drinks. Pets are welcome too! If anyone has any dietary restrictions please let me know. We need volunteers to come early to set everything up, so please shoot me an email if you are interested. We will be having the picnic rain or shine! The tents we are setting up will be able to accomodate everyone. Bringing games like washers or cornhole is encouraged :)", start_time: "2016-09-26 04:00", end_time: "2016-09-26 15:30" },
  { group_id: 2, title: "Flag Football", description: "We will have a flag football game today at the field by 13th street. As usual we will need a couple of referees, so those of you that would like to participate but not compete please come forward. Afterward we plan on heading to the TGI Fridays around the corner for a few drinks and to unwind. We had quite a crowd last time so be prepared for spectators! ", start_time: "2016-10-11 05:00", end_time: "2016-10-11 16:00" },
  { group_id: 3, title: "Movie Night on the Lawn", description: "The movie choices for this night are Waterworld, The Cabinet of Dr. Caligari, or Porky's. We will vote the night of. I am bringing some microwavable popcorn for everyone, but feel free to bring some other snacks! Feel free to bring friends along, the lawn is big enough for all of us! Please stick around afterward to help with cleanup as well as hear important announcements about what we will be doing in the coming weeks.", start_time: "2016-08-23 01:00", end_time: "2016-08-23 14:00" },
  { group_id: 3, title: "LAN Party", description: "We will be playing Starcraft for this LAN party! Get ready to ramp up your APM and construct additional Pylons! This event will be one wild ride. We will have a teams tournament and a solo tournament. Sign up early to reserve a spot. It is $50 to compete, winner take all! Refreshments will be provided by the kind folks at Blizzard.", start_time: "2016-08-24 02:00", end_time: "2016-08-24 14:30" },
  { group_id: 3, title: "Drum Cirle", description: "We are going to meet up in Central Park for a good old fashioned drum circle. Bring your drums and feel the good vibrations. Feel free to bring some other cool instruments. Theremins, didgeridoos, and pan flute's are always excellent choices. Don't worry if you feel like you can't play music! All are welcome.", start_time: "2016-09-07 03:00", end_time: "2016-09-07 15:00" },
  { group_id: 3, title: "Fitness Day", description: "This event is all about being fit! We will start off with some yoga to get warmed up, then move into an exciting combination of anaerobic and aerobic exercises, then cool down with some light stretches. You will be sore the next day! No equipment is required, but you may want to bring a yoga mat, we will not provide any. We are expecting quite a turnout so we need volunteers to help lead exercises. You can sign up by sending me an email.", start_time: "2016-09-19 04:00", end_time: "2016-09-19 15:30" },
  { group_id: 3, title: "Pizza Party", description: "After all that fitness we need to put the pounds back on with some pizza! The pizza party is a member's only event. Pizza and beer will be provided. Come hungry, there will be a lot of pizza! We are also going to start planning the upcoming member appreciation BBQ. Get ready to think outside the box, we want to come up with a theme that will blow the last BBQ's theme out of the water. Also at the end of the event, we will be setting up a table outside to give some pizza away to strangers as a kind gesture to the community!", start_time: "2016-09-26 05:00", end_time: "2016-09-26 16:00" },
  { group_id: 3, title: "BBQ", description: "Woo! Its everyone's favorite event of the season, the BBQ! Theme TBD at the Pizza Party. This one will be even better than the last, we have outdone ourselves every time! Get ready people, the bar has been set high.", start_time: "2016-09-25 10:00", end_time: "2016-09-25 11:00" },
  { group_id: 4, title: "Annual Award Ceremony", description: "Save the date for our Annual Awards Ceremony. Dress up! This is a black tie affair. Every member is allowed one date for this prestigious occassion. This year we have two more guest speakers, including Pat Sajak! He is a friend of the group and will be sticking around after for autographs. The categories this year are secret! Anything can happen!", start_time: "2016-08-14 01:00", end_time: "2016-08-14 14:00" },
  { group_id: 4, title: "Street Campaign", description: "This street campaign is a big one. I know it is hard for us mimes to reach out to the public when we are not allowed to speak, but as mimes, with must stick with our proud traditions! This is the only way of life we have ever known. We will need volunteers to set up tables in key locations around the city. Start preparing for the campaign now, this is one of our most important outreach events.", start_time: "2016-08-18 02:00", end_time: "2016-08-18 14:30" },
  { group_id: 4, title: "Pet Swap", description: "Tired of your boring old pet? Hang out with another member's pet the whole day! This is a fun event we do every couple of months. Members only event!", start_time: "2016-08-26 03:00", end_time: "2016-08-26 15:00" },
  { group_id: 4, title: "Bingo Night", description: "More details to come!", start_time: "2016-09-07 04:00", end_time: "2016-09-07 15:30" },
  { group_id: 4, title: "Sponsor Charity Dinner", description: "We will be having a dinner to raise some money for a local charity. Our sponsor has agreed to match whatever we donate! Please bring your family and friends. The cost of admission is $15 per person. The meal will be three courses, salad/soup, entree, and dessert. More details to come!", start_time: "2016-09-29 05:00", end_time: "2016-09-29 16:00" },
  { group_id: 4, title: "Street Race", description: "5k, free tshirts and Gatorade, what more could you want?! Sign ups will be held two weeks before. We also need volunteers to help set everything up. The race will go on rain or shine!", start_time: "2016-09-30 07:00", end_time: "2016-09-30 09:00" },
  { group_id: 5, title: "Jump Rope for Heart", description: "Jump Rope For Heart (JRFH) is a national education and fundraising program jointly sponsored by SHAPE America and the American Heart Association. It promotes physical education and provides children with knowledge of heart disease and stroke while raising funds for cardiovascular disease research, stroke research, and health education.", start_time: "2016-08-21 01:00", end_time: "2016-08-21 14:00" },
  { group_id: 5, title: "Breakfast for Dinner", description: "We will be having a nice members only dinner featuring all breakfast foods and plenty of breakfast beverages (ie Bloody Marys and Mimosas). This is a casual event. Please bring a side dish! Pancakes and eggs will be provided. Some good side dishes are sausages, bacon, hash browns, etc... Please email me about dietary restrictions!", start_time: "2016-08-26 02:00", end_time: "2016-08-26 14:30" },
  { group_id: 5, title: "Pumpkin Tossing Contest", description: "This event cultivates the odd, challenging, and competitive quest for distance that inspires creativity, ingenuity, teamwork, and passion. It is this very dedication that drives teams to compete using science and engineering skills and brings spectators to the gate which allows us to continue our never ending thirst to support our scholarship and charitable programs.", start_time: "2016-09-01 03:00", end_time: "2016-09-01 15:00" },
  { group_id: 5, title: "Bake Sale", description: "We will be hosting a bake sale to benefit a local charity. Please list all of your ingredients with your baked good! Store bought items are absolutely welcome as well! There is also going to be a 50/50. Raffle tickets will be sold during the event. Light refreshments will be provided!", start_time: "2016-09-02 04:00", end_time: "2016-09-02 15:30" },
  { group_id: 5, title: "Potluck", description: "To participate in the potluck dinner, all you have to do is bring a food item to share with everyone. A Google doc will be started a week before and sent to all RSVPing members. You will be able to include plus ones, and the item you are bringing on the doc. Store bought items are ok. Soda's and other soft beverages will be provided. Please keep in mind that we do need plates, napkins, and utensils.", start_time: "2016-09-03 05:00", end_time: "2016-09-03 16:00" },
  { group_id: 5, title: "Beach Day", description: "We all will be going to the beach. Please feel free to invite whoever and bring your pets! We will all meet up at the beach by Redding Ave (shoot me an email if you don't know where that is). Keep in mind the beach does have a no alcohol policy, and is a non-smoking beach. Toward the evening we will have a bonfire!", start_time: "2016-09-04 06:00", end_time: "2016-09-04 16:30" },
  { group_id: 5, title: "Habitat For Humanity Day 1", description: "Habitat for Humanity International (HFHI), generally referred to as Habitat for Humanity or simply Habitat, is an international, non-governmental, and nonprofit organization, which was founded in 1976. Habitat has been devoted to building 'simple, decent, and affordable' housing. Come and join us help this super great organization! We will be helping a team build a home in rural New York. About 2 and a half hours from Manhattan.", start_time: "2016-09-05 07:00", end_time: "2016-09-05 17:00" },
  { group_id: 5, title: "Habitat For Humanity Day 2", description: "Habitat for Humanity International (HFHI), generally referred to as Habitat for Humanity or simply Habitat, is an international, non-governmental, and nonprofit organization, which was founded in 1976. Habitat has been devoted to building 'simple, decent, and affordable' housing. Come and join us help this super great organization! We will be helping a team build a home in rural New York. About 2 and a half hours from Manhattan. This is a continuation of the first day! Feel free to attend one and not the other.", start_time: "2016-09-06 08:00", end_time: "2016-09-06 17:30" },
  { group_id: 6, title: "Open Bar", description: "We will be hosting an open bar in celebration of one of our member's recent marriage! Fun is to be had by all. We are asking for $15 per person, which will cover everything including tip for the bartender. We also have contacted a local cab company. They have agreed to transport guests of the event for 25% less than the Uber rate. Get ready for a good time! You must be 21 or older to attend this event.", start_time: "2016-08-23 01:00", end_time: "2016-08-23 14:00" },
  { group_id: 6, title: "Networking With the Stars", description: "This is another Meetup_Clone groups's event that we will be attending as a group. It is a change for people of all walks of life to meet people in their field and start networking. It is called Networking with the stars because every event there is one celebrity guest. This time around the guest will be Joyce Dewitt of Three's Company fame!", start_time: "2016-08-25 02:00", end_time: "2016-08-25 14:30" },
  { group_id: 6, title: "Karaoke Night", description: "We will be having a Karaoke Night at the sport's bar across the street from our usual meeting place. The bar has agreed to donate 15% of sales of the drinks we purchase to a local charity, so drink up! There will be a karaoke competition as well. The winner will get a $20 gift card to the bar and bragging rights! Let me know if you are going to bring a friend so I know how many wristband's to order (this is how they know we are buying drinks).", start_time: "2016-08-26 03:00", end_time: "2016-08-26 15:00" },
  { group_id: 6, title: "Dinner For Breakfast", description: "We will be sharing a morning meal based on healthy dinner food. Please bring a nice light item to share. Feel free to bring some likeminded friends who refuse the poisonous breakfast food culture!", start_time: "2016-09-15 04:00", end_time: "2016-09-15 15:30" },
  { group_id: 6, title: "Hudson River Cleanup", description: "We are partnering with a local conservation charity to help clean up the Hudson. We will take kayaks out to the river and pick up any trash we can find. Bagged lunches will be provided by the charity. The choices are turkey, ham, or vegetarian sandwiches. I need to send all the appropriate information to the charity a week before. So expect an invite to a Google doc about two weeks before the event! Invite your friends!", start_time: "2016-09-21 01:00", end_time: "2016-09-21 16:00" },
  { group_id: 7, title: "Yankees Game", description: "We will all be attending a Yankees game for dollar dog night. They will be playing the Philadelphia Phillies. We will try to get to the stadium about 4 hours beforehand for tailgating fun! If anyone has any tailgating games like Can Jam or Cornhole, please bring it!", start_time: "2016-08-20 01:00", end_time: "2016-08-20 14:00" },
  { group_id: 7, title: "Soup Kitchen", description: "For this event we have teamed up with a local charity that runs a soup kitchen about 5 blocks from our usual meeting place. It is going to be a rewarding experience and a great way to give back to the community with good friends.", start_time: "2016-08-27 02:00", end_time: "2016-08-27 14:30" },
  { group_id: 7, title: "Clothing Drive", description: "We are going to be collecting clothes to donate to the Salvation Army. Stop by and donate your clothes! We will need about 5 volunteers to run the event. For those of you volunteering please arrive an hour before the start of the event.", start_time: "2016-09-03 03:00", end_time: "2016-09-10 15:00" },
  { group_id: 7, title: "New York State Curling Championship Day 1", description: "The CURLING CHAMPIONS TOUR (CCT) has established a unique cohesive competition series. Comparable to several World Cups, the PGA- or ATP Tour the top events of European Curling competitions (for Men, Women & Juniors) have been brought together so the best European, North American and Asian teams will challenge each other with attractive and spectacular shot-making.", start_time: "2016-09-10 04:00", end_time: "2016-09-10 15:30" },
  { group_id: 7, title: "New York State Curling Championship Day 2", description: "The CURLING CHAMPIONS TOUR (CCT) has established a unique cohesive competition series. Comparable to several World Cups, the PGA- or ATP Tour the top events of European Curling competitions (for Men, Women & Juniors) have been brought together so the best European, North American and Asian teams will challenge each other with attractive and spectacular shot-making.", start_time: "2016-09-17 05:00", end_time: "2016-09-17 16:00" },
  { group_id: 8, title: "National Lemur Day", description: "We will be meeting to celelbrate National Lemur Day. We will watch a lemur documentary from National Geographic. Light refreshments will be provided. Please feel free to invite any friends to this awesome event for an awesome day!", start_time: "2016-08-02 01:00", end_time: "2016-08-02 14:00" },
  { group_id: 8, title: "Free All the Lemurs from the Zoo", description: "We will be discussing our Philadelphia affiliate organization's recent success in freeing all the Lemur's from the Philadelphia Zoo, and see if we can utilize their tactics to acheive the same goal. No ideas are off the table when it comes to lemur liberation. Come ready to discuss ideas from the radical to the mundane. Please come with open minds!", start_time: "2016-08-09 02:00", end_time: "2016-08-09 14:30" },
  { group_id: 8, title: "Lobster Dinner", description: "We got a great deal on lobster from Red Lobster! We will be having an all expenses paid Lobster dinner at our usual meeting spot! This dinner is to honor all the hard work our dedicated members have been working. Members only! You may bring only one guest. Alochol will be BYOB. If anyone would like to bring dessert, that would be super helpful.", start_time: "2016-08-16 03:00", end_time: "2016-08-16 15:00" },
  { group_id: 8, title: "Annual PFL National Congress", description: "Our parent organiztion, People for Lemurs, is having its national congress right in Manhattan! We must elect a member of our organization to go as a representative. The rest of us can go as spectators to the congress. The convention center it is at is really fun!", start_time: "2016-08-23 04:00", end_time: "2016-08-23 15:30" },
  { group_id: 8, title: "Lemur Art", description: "We are going to be showcasing a bunch of artwork featuring lemur's. The artists are all local and offering their work for a decent price. All sales are final! All types of art will be available, sculpture, pottery, paintings, etc... Feel free to come by and check out the artwork even if you do not plan to buy any.", start_time: "2016-08-30 05:00", end_time: "2016-08-26 16:00" },
  { group_id: 9, title: "Stamp Act Celebration", description: "Tonight's event will be a party to celebrate the Stamp Act! Alcohol will be provided, along with hors d'oeuvres. There will also be dancing. One of our members has kindly volunteered to DJ the event. Feel free to bring any food or drink, just make sure the ingredients are listed!", start_time: "2016-08-17 01:00", end_time: "2016-08-17 14:00" },
  { group_id: 9, title: "Pony Express Jubilee", description: "The Pony Express Jubilee is the main event! Stamp collectors from all over the tri-state area will be in attendance. As the flagship chapter, we need one of our members to give a speech at the beginning of dinner. It is a prestigious event so wear formal attire.", start_time: "2016-08-24 02:00", end_time: "2016-08-24 14:30" },
  { group_id: 9, title: "Rage Against Email", description: "We will be out by city hall protesting the state's new law that gives an unfair advantage of email over postage. This is obviously outrageous! Join us in a day of protest against this egregious piece of legislation.", start_time: "2016-08-31 03:00", end_time: "2016-08-31 15:00" },
  { group_id: 9, title: "Collection Appraisal", description: "We will be hosting an appraisal event free for members and $10 for non members. A few local philatelists have agreed to do this for us. It will give our group lots of exposure! Be sure to get your collections appraised!", start_time: "2016-09-07 04:00", end_time: "2016-09-07 15:30" },
  { group_id: 9, title: "Silent Auction", description: "A silent auction will be hosted at 314 Broad St. Postage stamps are exclusively being auctioned. This month it is rumored that a rare 1988 Yuri Gagarian stamp will be available for auction (WOW!). Lets get a big showing for some great group exposure to other stamp collectors!", start_time: "2016-09-14 05:00", end_time: "2016-09-14 16:00" },
])

rsvps = Rsvp.create([
  { event_id: 1, user_id: 1, attending: true },
  { event_id: 1, user_id: 2, attending: true },
  { event_id: 1, user_id: 3, attending: true },
  { event_id: 1, user_id: 4, attending: true },
  { event_id: 1, user_id: 5, attending: true },
  { event_id: 2, user_id: 6, attending: true },
  { event_id: 2, user_id: 7, attending: true },
  { event_id: 2, user_id: 1, attending: true },
  { event_id: 2, user_id: 2, attending: true },
  { event_id: 2, user_id: 3, attending: true },
  { event_id: 2, user_id: 4, attending: true },
  { event_id: 2, user_id: 5, attending: true },
  { event_id: 3, user_id: 6, attending: true },
  { event_id: 3, user_id: 7, attending: true },
  { event_id: 4, user_id: 1, attending: true },
  { event_id: 4, user_id: 2, attending: true },
  { event_id: 4, user_id: 3, attending: true },
  { event_id: 5, user_id: 4, attending: true },
  { event_id: 5, user_id: 5, attending: true },
  { event_id: 5, user_id: 6, attending: true },
  { event_id: 5, user_id: 7, attending: true },
  { event_id: 6, user_id: 1, attending: true },
  { event_id: 7, user_id: 2, attending: true },
  { event_id: 7, user_id: 3, attending: true },
  { event_id: 8, user_id: 4, attending: true },
  { event_id: 8, user_id: 5, attending: true },
  { event_id: 8, user_id: 6, attending: true },
  { event_id: 8, user_id: 7, attending: true },
  { event_id: 8, user_id: 1, attending: true },
  { event_id: 9, user_id: 2, attending: true },
  { event_id: 9, user_id: 3, attending: true },
  { event_id: 9, user_id: 4, attending: true },
  { event_id: 9, user_id: 5, attending: true },
  { event_id: 9, user_id: 6, attending: true },
  { event_id: 9, user_id: 7, attending: true },
  { event_id: 10, user_id: 1, attending: true },
  { event_id: 12, user_id: 2, attending: true },
  { event_id: 12, user_id: 3, attending: true },
  { event_id: 12, user_id: 4, attending: true },
  { event_id: 12, user_id: 5, attending: true },
  { event_id: 13, user_id: 6, attending: true },
  { event_id: 13, user_id: 7, attending: true },
  { event_id: 13, user_id: 1, attending: true },
  { event_id: 13, user_id: 2, attending: true },
  { event_id: 13, user_id: 3, attending: true },
  { event_id: 14, user_id: 4, attending: true },
  { event_id: 15, user_id: 5, attending: true },
  { event_id: 15, user_id: 6, attending: true },
  { event_id: 15, user_id: 7, attending: true },
  { event_id: 16, user_id: 1, attending: true },
  { event_id: 16, user_id: 2, attending: true },
  { event_id: 17, user_id: 3, attending: true },
  { event_id: 17, user_id: 4, attending: true },
  { event_id: 17, user_id: 5, attending: true },
  { event_id: 17, user_id: 6, attending: true },
  { event_id: 18, user_id: 7, attending: true },
  { event_id: 18, user_id: 1, attending: true },
  { event_id: 18, user_id: 2, attending: true },
  { event_id: 19, user_id: 3, attending: true },
  { event_id: 19, user_id: 4, attending: true },
  { event_id: 19, user_id: 5, attending: true },
  { event_id: 19, user_id: 6, attending: true },
  { event_id: 19, user_id: 7, attending: true },
  { event_id: 19, user_id: 1, attending: true },
  { event_id: 19, user_id: 2, attending: true },
  { event_id: 20, user_id: 3, attending: true },
  { event_id: 20, user_id: 4, attending: true },
  { event_id: 21, user_id: 5, attending: true },
  { event_id: 21, user_id: 6, attending: true },
  { event_id: 21, user_id: 7, attending: true },
  { event_id: 21, user_id: 1, attending: true },
  { event_id: 22, user_id: 2, attending: true },
  { event_id: 22, user_id: 3, attending: true },
  { event_id: 23, user_id: 4, attending: true },
  { event_id: 24, user_id: 5, attending: true },
  { event_id: 24, user_id: 6, attending: true },
  { event_id: 24, user_id: 7, attending: true },
  { event_id: 24, user_id: 1, attending: true },
  { event_id: 24, user_id: 2, attending: true },
  { event_id: 25, user_id: 3, attending: true },
  { event_id: 25, user_id: 4, attending: true },
  { event_id: 25, user_id: 5, attending: true },
  { event_id: 30, user_id: 6, attending: true },
  { event_id: 30, user_id: 7, attending: true },
  { event_id: 31, user_id: 1, attending: true },
  { event_id: 31, user_id: 2, attending: true },
  { event_id: 31, user_id: 3, attending: true },
  { event_id: 31, user_id: 4, attending: true },
  { event_id: 31, user_id: 5, attending: true },
  { event_id: 31, user_id: 6, attending: true },
  { event_id: 32, user_id: 7, attending: true },
  { event_id: 32, user_id: 1, attending: true },
  { event_id: 32, user_id: 2, attending: true },
  { event_id: 32, user_id: 3, attending: true },
  { event_id: 32, user_id: 4, attending: true },
  { event_id: 32, user_id: 5, attending: true },
  { event_id: 32, user_id: 6, attending: true },
  { event_id: 33, user_id: 7, attending: true },
  { event_id: 33, user_id: 1, attending: true },
  { event_id: 34, user_id: 2, attending: true },
  { event_id: 35, user_id: 3, attending: true },
  { event_id: 35, user_id: 4, attending: true },
  { event_id: 36, user_id: 5, attending: true },
  { event_id: 36, user_id: 6, attending: true },
  { event_id: 36, user_id: 7, attending: true },
  { event_id: 36, user_id: 1, attending: true },
  { event_id: 37, user_id: 2, attending: true },
  { event_id: 37, user_id: 3, attending: true },
  { event_id: 37, user_id: 4, attending: true },
  { event_id: 38, user_id: 5, attending: true },
  { event_id: 38, user_id: 6, attending: true },
  { event_id: 38, user_id: 7, attending: true },
  { event_id: 38, user_id: 1, attending: true },
  { event_id: 39, user_id: 2, attending: true },
  { event_id: 39, user_id: 3, attending: true },
  { event_id: 39, user_id: 4, attending: true },
  { event_id: 40, user_id: 5, attending: true },
  { event_id: 40, user_id: 6, attending: true },
  { event_id: 41, user_id: 7, attending: true },
  { event_id: 41, user_id: 1, attending: true },
  { event_id: 42, user_id: 2, attending: true },
  { event_id: 43, user_id: 3, attending: true },
  { event_id: 43, user_id: 4, attending: true },
  { event_id: 43, user_id: 5, attending: true },
  { event_id: 44, user_id: 6, attending: true },
  { event_id: 44, user_id: 7, attending: true },
  { event_id: 44, user_id: 1, attending: true },
  { event_id: 45, user_id: 2, attending: true },
  { event_id: 45, user_id: 3, attending: true },
  { event_id: 45, user_id: 4, attending: true },
  { event_id: 45, user_id: 5, attending: true },
  { event_id: 45, user_id: 6, attending: true },
  { event_id: 46, user_id: 7, attending: true },
  { event_id: 46, user_id: 1, attending: true },
  { event_id: 47, user_id: 2, attending: true },
  { event_id: 47, user_id: 3, attending: true },
  { event_id: 47, user_id: 4, attending: true },
  { event_id: 47, user_id: 5, attending: true },
  { event_id: 47, user_id: 6, attending: true },
  { event_id: 48, user_id: 7, attending: true },
  { event_id: 48, user_id: 1, attending: true },
  { event_id: 48, user_id: 2, attending: true },
  { event_id: 48, user_id: 3, attending: true },
  { event_id: 48, user_id: 4, attending: true },
  { event_id: 48, user_id: 5, attending: true },
  { event_id: 48, user_id: 6, attending: true },
  { event_id: 49, user_id: 7, attending: true },
  { event_id: 49, user_id: 1, attending: true },
  { event_id: 49, user_id: 2, attending: true },
  { event_id: 49, user_id: 3, attending: true },
  { event_id: 49, user_id: 4, attending: true },
  { event_id: 49, user_id: 5, attending: true },
  { event_id: 50, user_id: 6, attending: true },
  { event_id: 50, user_id: 7, attending: true },
  { event_id: 50, user_id: 1, attending: true },
  { event_id: 50, user_id: 2, attending: true },
  { event_id: 50, user_id: 3, attending: true },
  { event_id: 50, user_id: 4, attending: true },
  { event_id: 50, user_id: 5, attending: true },
  { event_id: 51, user_id: 6, attending: true },
  { event_id: 51, user_id: 7, attending: true },
  { event_id: 51, user_id: 1, attending: true },
  { event_id: 51, user_id: 2, attending: true },
  { event_id: 51, user_id: 3, attending: true },
  { event_id: 52, user_id: 4, attending: true },
  { event_id: 52, user_id: 5, attending: true },
  { event_id: 52, user_id: 6, attending: true },
  { event_id: 52, user_id: 7, attending: true },
  { event_id: 52, user_id: 1, attending: true },
  { event_id: 52, user_id: 2, attending: true },
  { event_id: 52, user_id: 3, attending: true },
])
